#### Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
import numpy as np
a=np.array([[1,2,7,4],[9,12,8,10]])
b=np.array([[16,34,31,20],[1,9,45,66]])
print(a>b)

[[False False False False]
 [ True  True False False]]


In [3]:
print(a>=b)

[[False False False False]
 [ True  True False False]]


In [4]:
print(a<b)

[[ True  True  True  True]
 [False False  True  True]]


In [5]:
print(a<=b)

[[ True  True  True  True]
 [False False  True  True]]


#### Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [11]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
print(np.array([a,b,c]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


#### Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array


In [20]:
a=np.array([[1,5,7],[2,9,10]])
print(a)
print("-----------------------------------")
print(np.sum(a,axis=0)) 
print("-----------------------------------------------")
print(np.sum(a,axis=1))
print("---------------------------------------")
print(np.sum(a))


[[ 1  5  7]
 [ 2  9 10]]
-----------------------------------
[ 3 14 17]
-----------------------------------------------
[13 21]
---------------------------------------
34


#### Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [22]:
a=np.array([[10,20,30,40],[50,60,70,80]])
b=np.array([[1,2,3,4],[5,6,7,8]])
print(np.add(a,b))

[[11 22 33 44]
 [55 66 77 88]]


In [23]:
print(np.subtract(a,b))

[[ 9 18 27 36]
 [45 54 63 72]]


In [24]:
print(np.multiply(a,b))

[[ 10  40  90 160]
 [250 360 490 640]]


In [25]:
print(np.divide(a,b))

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]


#### Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [28]:
print(np.sin(np.array([0,30,60,90])*np.pi/180))

[0.        0.5       0.8660254 1.       ]


In [29]:
print(np.cos(np.array([0,30,60,90])*np.pi/180))

[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]


In [30]:
print(np.tan(np.array([0,30,60,90])*np.pi/180))

[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]


#### Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [14]:
import pandas as pd
d={"Name":["Manoj","Madhu","sai","Teju","Pavan"],"Score":[12,14,11,10,15],"Branch":["CSE","EEE","ECE","IT","IT"]}
print(d)

{'Name': ['Manoj', 'Madhu', 'sai', 'Teju', 'Pavan'], 'Score': [12, 14, 11, 10, 15], 'Branch': ['CSE', 'EEE', 'ECE', 'IT', 'IT']}


In [15]:
df=pd.DataFrame(d,index=["a","b","c","d","e"])
print(df)

    Name  Score Branch
a  Manoj     12    CSE
b  Madhu     14    EEE
c    sai     11    ECE
d   Teju     10     IT
e  Pavan     15     IT


#### Question 7:
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [16]:
df1=df[["Name","Score"]]
print(df1)

    Name  Score
a  Manoj     12
b  Madhu     14
c    sai     11
d   Teju     10
e  Pavan     15


#### Question 8:
Write a Pandas program to join the two given dataframes along rows and assign all data.

In [17]:
data={"Age":[19,18,17,18,18],"City":["Hyd","Bvrm","Bvrm","Mumbai","Delhi"]}
df2=pd.DataFrame(data,index=["a","b","c","d","e"])
print(df2)

   Age    City
a   19     Hyd
b   18    Bvrm
c   17    Bvrm
d   18  Mumbai
e   18   Delhi


In [18]:
print(df.join(df2))

    Name  Score Branch  Age    City
a  Manoj     12    CSE   19     Hyd
b  Madhu     14    EEE   18    Bvrm
c    sai     11    ECE   17    Bvrm
d   Teju     10     IT   18  Mumbai
e  Pavan     15     IT   18   Delhi



#### Question 9:
Write a Pandas program to detect missing values of a given DataFrame. Display True or False

In [20]:
import numpy as np
data = {'First Score':[100, 90, np.nan, 95], 
        'Second Score': [30, 45, 56, np.nan], 
        'Third Score':[np.nan, 40, 80, 98]} 
print(data)

{'First Score': [100, 90, nan, 95], 'Second Score': [30, 45, 56, nan], 'Third Score': [nan, 40, 80, 98]}


In [22]:
df3=pd.DataFrame(data)
print(df3)

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0


In [23]:
print(df3.isnull())

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False


#### Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data

In [26]:
s=pd.Series(np.arange(6),index=["a","b","c","d","e","f"])
print(s)

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32
